---
- hosts: all
  remote_user:virus
  pre_tasks:
    - name: Check if host is running
      ping:
      register: ping_result
      failed_when: ping_result.ping != 'pong'

  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send notification to Discord if reboot is required
      uri:
        url: https://discord.gg/BkbRpESy
        method: POST
        body_format: json
        body:
          content: "Host {{ inventory_hostname }} is running. Reboot required: {{ reboot_required.stat.exists }}"
      when: reboot_required.stat.exists == True and ping_result.ping == 'pong'
