---
- hosts: target
  become: yes
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send message to Discord if reboot is required
      uri:
        url: https://discord.gg/bd8gPsbxEQ

        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          content: 'Reboot is required on the host system.'
      when: reboot_required.stat.exists
...
