---
# ansible-playbook your_playbook.yml --tags "update_debian"
# ansible-playbook your_playbook.yml --tags "update_redhat"

- hosts: hostgroup1
  tasks:
    - name: Update Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      tags:
        - update_debian

    - name: Update Red Hat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      tags:
        - update_redhat

