---
- hosts: your_host
  tasks:
    - name: Update Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update Red Hat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

